### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-cpp#202]
The README states the repo is work in progress and code will be here soon. I think we could probably remove the WIP part (a project is always WIP) and include more useful information for developers.

I'd expect to have the common information like you see with other Function Frameworks.

Here is an example:

https://github.com/GoogleCloudPlatform/functions-framework-dart

**Comment by coryan** [comment]
Partially a dup of #59

**Comment by coryan** [comment]
@grant AFAICT we achieved parity on the README with other frameworks.  If I missed something (this is likely) please let me know what specifically needs fixing.
