### ISSUE TITLE
Is Cloud Functions support planned?

### ISSUE THREAD

**Issue by leo60228** [GoogleCloudPlatform/functions-framework-cpp#262]
The README says that it isn't *currently* supported, but it's unclear on whether it will be in the future.

**Comment by coryan** [comment]
Thanks for your interest in this project.

At this time, we do not have a roadmap that we can share in this forum.  Meanwhile:

* You can deploy functions based on this framework to [Cloud Run][run-overview]
   - See [this guide][howto-cloud-run] for details.
 * If you are using CloudEvent, you can use [eventarc][eventarc-overview] to setup triggers for Cloud Run
    - See [this guide][howto-cloud-event] for details.
    
Please send us any feedback you might have, including whether we support your use-case well or we could do better.

[run-overview]: https://cloud.google.com/run
[eventarc-overview]: https://cloud.google.com/eventarc
[howto-cloud-run]: https://github.com/GoogleCloudPlatform/functions-framework-cpp/tree/main/examples/site/howto_deploy_to_cloud_run
[howto-cloud-event]: https://github.com/GoogleCloudPlatform/functions-framework-cpp/tree/main/examples/site/howto_deploy_cloud_event

**Comment by coryan** [comment]
Closing as there does not seem to be further questions.
